// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbG564TnnsI2AYq9iEvXEAgTyzVkjKKpE',
    appId: '1:927412940351:web:b91cc95ed2c65fb768128a',
    messagingSenderId: '927412940351',
    projectId: 'db-color-sense',
    authDomain: 'db-color-sense.firebaseapp.com',
    storageBucket: 'db-color-sense.firebasestorage.app',
    measurementId: 'G-8C9QKHS11V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_NREykZYBSf6-YxvX4MXLMkgvrMYchk',
    appId: '1:927412940351:android:564b73de85f376a068128a',
    messagingSenderId: '927412940351',
    projectId: 'db-color-sense',
    storageBucket: 'db-color-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-Eckzq5AnYFwuTbFT84u3YFHWa6Pijo',
    appId: '1:927412940351:ios:b4baf0e4e4a3e54968128a',
    messagingSenderId: '927412940351',
    projectId: 'db-color-sense',
    storageBucket: 'db-color-sense.firebasestorage.app',
    iosBundleId: 'com.example.colorsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS-Eckzq5AnYFwuTbFT84u3YFHWa6Pijo',
    appId: '1:927412940351:ios:b4baf0e4e4a3e54968128a',
    messagingSenderId: '927412940351',
    projectId: 'db-color-sense',
    storageBucket: 'db-color-sense.firebasestorage.app',
    iosBundleId: 'com.example.colorsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbG564TnnsI2AYq9iEvXEAgTyzVkjKKpE',
    appId: '1:927412940351:web:bc1fbc37bf25269a68128a',
    messagingSenderId: '927412940351',
    projectId: 'db-color-sense',
    authDomain: 'db-color-sense.firebaseapp.com',
    storageBucket: 'db-color-sense.firebasestorage.app',
    measurementId: 'G-HPQGEHEW2E',
  );
}
